function MatrixA = gyromatrixA(thxT,thyT,thzT,thxTdot,thyTdot,thzTdot,thxTddot,thyTddot,thzTddot,thy,thz,thydot,thzdot,Ic1x,Ic1y,Ic1z,Ic2x,Ic2y,Ic2z,Igax,Igtr,Im,C1damping,C2damping,spinspeed)
%GYROMATRIXA
%    MATRIXA = GYROMATRIXA(THXT,THYT,THZT,THXTDOT,THYTDOT,THZTDOT,THXTDDOT,THYTDDOT,THZTDDOT,THY,THZ,THYDOT,THZDOT,IC1X,IC1Y,IC1Z,IC2X,IC2Y,IC2Z,IGAX,IGTR,IM,C1DAMPING,C2DAMPING,SPINSPEED)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    27-May-2023 18:36:41

t2 = cos(thy);
t4 = Im./4.0;
t3 = t2.^2;
MatrixA = reshape([Ic2y+Igtr+t4,0.0,0.0,Ic2x+Ic1z+Igax+t4-Ic2x.*t3+Ic2z.*t3-Igax.*t3+Igtr.*t3],[2,2]);
